### ISSUE TITLE
Featured Status Request Wunduniik Chapter III

### ISSUE THREAD

**Issue by Alaxouche** [wabbajack-tools/Requests-Reports#10]
### What game is your list for ?

TES Skyrim Special Edition

### What is your List Called ?

Wunduniik - Chapter III

### Where do you offer support for your list ?

https://discord.gg/alaxouche-s-skyrim-hub-750268919201398805 

### Link to Readme / Documentation

https://www.wunduniikwiki.com

### Find A Modlist Assets and Meta Information

Wunduniik is a heavy +3000 mods list created by me ([Alaxouche](https://next.nexusmods.com/profile/AlaxoucheModding/about-me?gameId=1704)) from the ground up, based on my original [A Photorealistic Fantasy Tamriel Guide](https://www.nexusmods.com/skyrimspecialedition/mods/46382). It improves almost everything from the vanilla game to make it looks more like a 2023 game than a 2011 game. Keep in mind that the list is more like a vanilla rework than a list adding new quests, new lands... This list is made for Skyrim SE + the 4 free DLCs. This list is meant to be mainly a graphical remaster, even if overhauling everything. A french version is being built and included in the profiles.

[Load Order Library ](https://loadorderlibrary.com/lists/my-list-22)
[Changelog](https://www.wunduniikwiki.com/changelog)
[Modlist Showcases, Reviews and Trailers](https://youtube.com/playlist?list=PLKFYXXObsDxpgRCHuzaWXhRHwt_M6PYjw&si=m0TY_GUFQAIWXZZX)

![Patreon Gold Sword square](https://github.com/wabbajack-tools/Requests-Reports/assets/93254859/e75fbd95-0d9b-40c1-91a7-33fb1e402ac8)

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/Alaxouche/Wunduniik/main/Wunduniik-Logo-v2.6.1.webp

### When did you release the list on the Wabbajack UI?

Around April 2023 (Nexus Reposit was created 20 April 2023)

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by NotTotal** [comment]
Reject.
Please update your readme to comply with the wabbajack monetization policy. Paywalled mods cannot be implied to be required, necessary, or the only way to achieve good performance. You may still recommend paywalled mods as long as it meets these requirements. This is not the reason for rejection, but you will need to fix it.

Support was visible and clearly provided as required. However it appears the list is generally unstable and frequently crashes. While the crashes are being addressed, the quantity is concerning.

Given the recently reported crashes and previous requests for featured failing on the patching of this list I chose to take a closer look at the xedit. There are numerous custom patches, but the list is **not** properly patched. Some of the custom patches instead overwrite each other, or are overwritten by inapplicable nexus patches. Notably there is little to no patching of leveled lists, container records, or the non-visual aspects of race and npc records resulting in many mods being wholly or partially overwritten. Additionally, there does not appear to be any fixing or patches to the many mihail mods used. Mihail plugins are generally a mess and should be carefully examined, cleaned, and fixed before allowed in a list. 

I have included an assortment of xedit issues I found while examining this list. This is not an exhaustive list and only represents about 20% of the notable issues I found before determining the patching was insufficient. Please run a check for conflicts in xedit and start fixing things. Your list will not be granted featured status until the majority of the issues that show up in an xedit conflict check have been addressed.  

![firefox_Hsptk3CZ97](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/c8828ffd-1d24-4023-9ef0-6367baffe7f5)
![SSEEdit64_A38ECpisT9](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/1ec3d205-b072-4a6c-87ab-b930ade90f2d)
![SSEEdit64_e7b5YYAgQA](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/69ef49e5-021d-4b45-ae01-36e22cd91549)
![SSEEdit64_ffBxnjVuPy](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/60120199-8477-4610-b731-d059d922cb6b)
![SSEEdit64_g8mO6Xewc8](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/bc0e0491-354f-431f-96d1-90616789d7eb)
![SSEEdit64_HcLY3Emu2e](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/20bf7e2b-8846-44c2-b5d8-fb62de0ed55e)
![SSEEdit64_J3x5qra633](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/1105d100-312d-4e22-b6c0-2c4a9f97a377)
![SSEEdit64_JDdrdhv0On](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/1542b40c-7507-4566-924d-9ca3c880dc03)
![SSEEdit64_K1vMLVs09m](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/749886f3-d6c9-45fc-9f31-8e020fb3632d)
![SSEEdit64_KbAjgsJZtB](https://github.com/wabbajack-tools/Requests-Reports/assets/22380834/1c1a723b-91b6-411c-9343-5ead91de062d)
