### ISSUE TITLE
Featured Status Request Viva New Vegas

### ISSUE THREAD

**Issue by Ungeziefi** [wabbajack-tools/Requests-Reports#11]
### What game is your list for ?

Fallout New Vegas

### What is your List Called ?

Viva New Vegas

### Where do you offer support for your list ?

https://discord.gg/S99Ary5eba

### Link to Readme / Documentation

https://vivanewvegas.moddinglinked.com/wabbajack.html

### Find A Modlist Assets and Meta Information

1 - https://raw.githubusercontent.com/Ungeziefi/VNV-Wabbajack/main/Image.png
2 - Viva New Vegas, by Ungeziefi.
3 - https://vivanewvegas.moddinglinked.com/
4 - Ultimate Edition of FNV or the base game + all DLCs and pre-order content.
5 - Viva New Vegas is a Vanilla Plus modlist for Fallout New Vegas, it features many improvements across the board without drastically overhauling the core experience or straying away from the game's original intent.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/Ungeziefi/VNV-Wabbajack/main/Image.webp

### When did you release the list on the Wabbajack UI?

30/4/2024

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by Drazden** [comment]
Approved in 24 hours unless anyone has objections.

Suggestions:
-Mention Wabbajack does not support Epic Games *or* Gamepass, as well as PCR and German versions

**Comment by Ungeziefi** [comment]
The page on ModdingLinked people are linked to mentions that.
