### ISSUE TITLE
Featured Status Request for Squeegeepunk

### ISSUE THREAD

**Issue by ThirdEyeSqueegee** [wabbajack-tools/Requests-Reports#12]
### What game is your list for ?

Cyberpunk 2077

### What is your List Called ?

Squeegeepunk

### Where do you offer support for your list ?

https://discord.gg/WF66mMu

### Link to Readme / Documentation

https://github.com/ThirdEyeSqueegee/Squeegeepunk/blob/main/README.md

### Find A Modlist Assets and Meta Information

1. Banner image: https://github.com/ThirdEyeSqueegee/Squeegeepunk/blob/main/assets/Squeegeepunk.png
2. List name: Squeegeepunk / Author: ThirdEyeSqueegee
3. "Find out more" link: https://github.com/ThirdEyeSqueegee/Squeegeepunk
4. Nothing besides base game required
5. N/A

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/ThirdEyeSqueegee/Squeegeepunk/main/assets/Squeegeepunk.webp

### When did you release the list on the Wabbajack UI?

6/14/2024

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by NotTotal** [comment]
Rejected. Apply again once the list has been on the UI for 30 days.
