### ISSUE TITLE
Featured Status Request [NGVO]

### ISSUE THREAD

**Issue by biggie-boss** [wabbajack-tools/Requests-Reports#18]
### What game is your list for ?

TES Skyrim Special Edition

### What is your List Called ?

NGVO

### Where do you offer support for your list ?

discord.gg/bungalo

### Link to Readme / Documentation

https://github.com/biggie-boss/NGVO/tree/main

### Find A Modlist Assets and Meta Information

1 - https://camo.githubusercontent.com/88c5caf58a561dd1bdbfeccc89d4a54bac447c7c572934faa75ebcc82d32b586/68747470733a2f2f73746174696364656c69766572792e6e657875736d6f64732e636f6d2f6d6f64732f313730342f696d616765732f3131393937322f3131393937322d313731363338313238382d3532313137303734342e706e67
2 - NGVO (Next Generation Visual Overhaul) by biggie_boss
3 - https://ngvo.netlify.app/
4 - Requires Special Edition & Creation Kit for Special Edition (No AE content needed)
5 - Visual-only modlists. It would be most likely the heaviest among them.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://camo.githubusercontent.com/88c5caf58a561dd1bdbfeccc89d4a54bac447c7c572934faa75ebcc82d32b586/68747470733a2f2f73746174696364656c69766572792e6e657875736d6f64732e636f6d2f6d6f64732f313730342f696d616765732f3131393937322f3131393937322d313731363338313238382d3532313137303734342e706e67

### When did you release the list on the Wabbajack UI?

May 2024

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by NotTotal** [comment]
Approved. Please check the attached minor issues and verify that they're correct. 
![SSEEdit64_4sTHHXV1G3](https://github.com/user-attachments/assets/894742e8-abdb-40e2-ac15-8c4eba2776fa)
![SSEEdit64_hE03JRcfQT](https://github.com/user-attachments/assets/f465520f-9ee0-40d1-acb1-224b28334fda)
![SSEEdit64_KMZ1RH40fn](https://github.com/user-attachments/assets/a7d4ea02-af7a-4458-bafd-70e9711a2256)
![SSEEdit64_mt2nHrgWmV](https://github.com/user-attachments/assets/67bdeffc-6c2b-43ea-b50e-7f06d8e128c3)
![SSEEdit64_pKg3Rt3nx9](https://github.com/user-attachments/assets/ab86811e-7c1b-4ceb-8fbe-78a124dfd49d)
![SSEEdit64_Znf2zBrLBX](https://github.com/user-attachments/assets/67634bc5-e291-42b9-8d39-e826cd13570c)
![SSEEdit64_Zvi2lbuFUG](https://github.com/user-attachments/assets/5f5d7d86-e386-44c4-bc95-26ba219075dd)
