### ISSUE TITLE
Featured Status Request [Listonomicon]

### ISSUE THREAD

**Issue by ajaxxxxxxxx** [wabbajack-tools/Requests-Reports#19]
### What game is your list for ?

Baldur's Gate 3

### What is your List Called ?

Listonomicon

### Where do you offer support for your list ?

https://discord.gg/boneyard-creations-415287319982112768

### Link to Readme / Documentation

https://www.modlists.net/docs/7listo/Home

### Find A Modlist Assets and Meta Information

1. https://github.com/Listonomicon-Team/Listonomicon/blob/main/Listo%20Banner%20for%20Gallery.webp
2. List name: "Listonomicon." Authors: Ajax and LillyBird
3. https://www.modlists.net/docs/7listo/Home (readme)
4. Baldur's Gate 3 Mod Manager (included in wabba distro), BG3 Script Extender (obtained through the mod manager)
5. Listonomicon is the only active BG3 list. We see it as a Vanilla+ that seeks to add more content and QoL features to a second playthrough of the game. I guess it would fit into BG3 -> Vanilla but better as a category?

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://github.com/Listonomicon-Team/Listonomicon/blob/main/Listo%20Banner%20for%20Gallery%2016x9.webp

### When did you release the list on the Wabbajack UI?

April 2024

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by TDarkShadow** [comment]
Hey Ajax,

Apologies for the delay.
I'm currently waiting on https://github.com/reyqune/ to document their findings.
We're looking into providing feedback, and wether or not it's approved to be featured, as soon as possible.

With friendly greetings, TDarkShadow

**Comment by TDarkShadow** [comment]
One thing needs to be done before it can be approved.

You need to modify your [NexusMods page](https://www.nexusmods.com/baldursgate3/mods/8976?tab=description)'s permissions to adhere to our CC BY-NC-SA 4.0 policy.
This means your modlist is open for modification, conversion and asset use without your permission.

Other than that, I'm checking some additional context but I don't see an argument to block your request.

**Comment by ajaxxxxxxxx** [comment]
Thank you again for checking in on my request TDarkShadow.
I pushed a 2.0 update to Listo today to address (by either fixing, or eliminating the root need) Reyqune's requirements. I have let Reyqune know via Discord and look forward to an update on my request. :)

**Comment by TDarkShadow** [comment]
https://github.com/reyqune/ gave feedback the modlist is installable and playable without issues.
Support server looks organized and welcoming.
Featured request approved in ~24hrs unless anyone has objections.

**Comment by TDarkShadow** [comment]
Approved.
