### ISSUE TITLE
Featured Status Request [Apostasy]

### ISSUE THREAD

**Issue by aljoxo** [wabbajack-tools/Requests-Reports#20]
### What game is your list for ?

TES Skyrim

### What is your List Called ?

Apostasy

### Where do you offer support for your list ?

discord.gg/WakingDreams

### Link to Readme / Documentation

https://github.com/Oghma-Infinium/Apostasy/

### Find A Modlist Assets and Meta Information

1. https://raw.githubusercontent.com/Oghma-Infinium/Apostasy/main/images/banner.webp
2. Apostasy / aljo
3. https://github.com/Oghma-Infinium/Apostasy/ <-- All documentation
4. Requires free AE update (not the paid Anniversary Edition update, just the newest version of Skyrim off Steam)
5. Wabbakinator: Skyrim --> Skyrim --> something other than vanilla --> No LOTD --> Lore friendly --> No Requiem --> Vanilla combat bores me --> Challenging combat --> Highly curated experience with custom content and overhauls
Figma: Down near Aldrnari (custom content and overhauls)

**Notes Regarding Figma/Wabbakinator Placement**
- Aldrnari is also a list known for custom content, however Aldrnari's custom content is primarily zelie's custom merges and mods recreated from other content (forked stuff from requiem for ex).
- Apostasy's custom content is primarily originally produced content (for example, a completely original and custom perk overhaul). Apostasy is also newer and more actively maintained than Aldrnari.
- Aldrnari and Apostasy are not very similar at all, but on the surface (and with the restrictions of the current "find a list" system, they are very close to each other - "Challenging Modern Combat with Custom Content and Overhauls")
- From a pure performance standpoint, Apostasy probably runs better than Aldrnari. I'm not sure if Apostasy's performance warrants the "Very Heavy List" tag as the majority of my testing for the list was done on a system with a 5800X and 2080 which held 50-60fps @ 1440p consistently. That said, the requirements I list in my readme are "buffed" to compensate for the fact Waking Dreams has a policy to not provide support for performance due to it almost always being a user-end issue.

**Other Links and Notes**
[Load Order Library](https://loadorderlibrary.com/lists/Apostasy) - patches are prefixed with `APO_`
[Nexus Page](https://www.nexusmods.com/skyrimspecialedition/mods/118893)

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/Oghma-Infinium/Apostasy/main/images/banner.webp

### When did you release the list on the Wabbajack UI?

July 11, 2024

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by SovnSkyrim** [comment]
As the maintainer of the chart; and sole developper of Aldrnari; I was gonna write that you're less focus on powerfantasy and custom enemies and highlight the custom content.
As in

What features are more important? 
- Powerfantasy EnaiRim with custom enemies
- Customized SimonRim with few custom enemies.

I wouldnt place it within the "Heavy list" category unless many users complain; my experience with it showed no issues to run it; and definitely a smoother time than with my own work.

**Comment by aljoxo** [comment]
Relevant info for featured

**List name:** Apostasy
**Author(s):** aljo
**Banner image/video (if video first frame is the thumbnail):** https://raw.githubusercontent.com/Oghma-Infinium/Apostasy/main/images/banner.webp
**(Optional) Up to 5 accompanying 16:9 showcase images:** Some of these screenshots may change depending on how they are viewed presentation wise on the site that is posting them.
1. https://staticdelivery.nexusmods.com/mods/1704/images/118893/118893-1720419196-1191687929.png
2. https://staticdelivery.nexusmods.com/mods/1704/images/118893/118893-1720520004-1902455222.png
3. https://staticdelivery.nexusmods.com/mods/1704/images/118893/118893-1720525985-188255669.png
4. https://staticdelivery.nexusmods.com/mods/1704/images/118893/118893-1720811383-481712445.png
5. **Pending next list update**

**Does the game require anything more than the base game? If yes, what does it require (any specific DLCs that are not included in the base game or the Anniversary Edition DLC count):** The list requires the four free creation club content included in the November 2021 update for Skyrim Special Edition.
**Up to 6 tags to define your modlist, these can be the same as the gallery ones:** "MCO", "Balanced", "Visuals", "Custom Content", "Skyrim Special Edition" (this tag may be redundant for this)
**A description up to 270 characters long (might need to be shorter based on modlist name and if requiring any DLCs, due to space constraints, will discuss on a modlist to modlist basis):** Apostasy is a modlist for Skyrim SE that offers a modern, action-oriented combat system, custom tailored gameplay, and a consistent, high-fidelity graphics overhaul. Apostasy aims to deliver a cohesive and refined experience, enhancing both visuals and mechanics.
**Find out more link (readme/wiki/etc):** https://github.com/Oghma-Infinium/Apostasy
**Community link (Discord, Guilded, etc):** https://discord.gg/4WwqfK5yHg _or_ https://discord.gg/WakingDreams

**Comment by NotTotal** [comment]
Approved.
