### ISSUE TITLE
Featured Status Request Baldur's Gate 3 Enhanced Edition

### ISSUE THREAD

**Issue by reyqune** [wabbajack-tools/Requests-Reports#22]
### What game is your list for ?

Baldur's Gate 3

### What is your List Called ?

Baldur's Gate 3 Enhanced Edition

### Where do you offer support for your list ?

https://discord.gg/ty62eQTdkE

### Link to Readme / Documentation

https://github.com/reyqune/Baldur-s-Gate-3-Enhanced-Edition/blob/main/README.md

### Find A Modlist Assets and Meta Information

_We use multiple things to promote lists to users who are unsure of which modlist to play. Please say where your list will fit in the following:_

 https://github.com/wabbajack-tools/mod-lists/blob/master/modlist-descriptions.md

https://github.com/wabbajack-tools/mod-lists/blob/master/modlist-descriptions.md#baldurs-gate-3

>https://wizard.wabbajack.org/

Baldur's Gate 3 -> Vanilla+

>https://tinyurl.com/mrkbfzwe

n/a, not Skyrim

link to banner image:
https://raw.githubusercontent.com/reyqune/Baldur-s-Gate-3-Enhanced-Edition/refs/heads/main/images/Banner.png

_2- list name and author:_
Baldur's Gate 3 Enhanced Edition; reyqune

_3- Find out more link:_
[https://github.com/reyqune/Baldur-s-Gate-3-Enhanced-Edition/tree/main](https://github.com/reyqune/Baldur-s-Gate-3-Enhanced-Edition/tree/main)

_4- Does the game require anything more than the base game? If yes, what does it require (any specific DLCs that are not included in the base game or the Anniversary Edition DLC count)_
no

_5- Where it fits in the chart/wizard and the differences between similar lists. Refer to the existing resources for an idea of what we are looking for._
Baldur's Gate 3 -> Vanilla+

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/reyqune/Baldur-s-Gate-3-Enhanced-Edition/main/images/banner.webp

### When did you release the list on the Wabbajack UI?

https://github.com/wabbajack-tools/mod-lists/pull/3557

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by NaoSouONight** [comment]
Played a good chunk of act 1, as of the most recent and up to date version of the game.
Works fine without any issues.

**Comment by ajaxxxxxxxx** [comment]
Installs correctly from gallery, launches correctly, seems to run fine without console errors and doesn't need custom patching to make mechanics work together. Left some feedback/thoughts with Reyqune on Discord on mods that could be removed or better versions that could be used but a lot of it is preference/judgement/taste.

**Comment by reyqune** [comment]
I have sorted the things mentioned in the feedback by Ajax.
The readme has been updated, and there's a new version of the list available.

**Comment by Alvadus** [comment]
Installation process is perfectly fine, everything works fine in-game without any issues and all mods are loaded correctly including script extender and MCM configs.

**Comment by reyqune** [comment]
thanks for the review!

**Comment by TDarkShadow** [comment]
Good documentation.
Runs perfectly as far as I can see.
Unsure if the game and/or modlist is installed in a secondary drive, but not have the hardware atm to test this edge case.
Only minor issue I've noticed is there is no Beta 7 branch in the Steam version, but this might be an artifact when the game had an update and broke some mods, I assume?
Support is superb and well explained.

Gonna mark this modlist as featured if there are no objections in ~24h.

**Comment by reyqune** [comment]
>Unsure if the game and/or modlist is installed in a secondary drive, but not have the hardware atm to test this edge case.

The list is setup to use the root builder setting copy by default, so it can be installed on a separate drive from the game itself.

>Only minor issue I've noticed is there is no Beta 7 branch in the Steam version, but this might be an artifact when the game had an update and broke some mods, I assume?

Will update the readme to remove that.
