### ISSUE TITLE
Featured Status Request Alpyne

### ISSUE THREAD

**Issue by Ferroxius** [wabbajack-tools/Requests-Reports#23]
### What game is your list for ?

TES Skyrim Special Edition

### What is your List Called ?

Alpyne

### Where do you offer support for your list ?

https://discord.gg/aetherius-modding

### Link to Readme / Documentation

https://raw.githubusercontent.com/Ferroxius/Palette/blob/main/Alpyne_Installation.md

### Find A Modlist Assets and Meta Information

https://github.com/wabbajack-tools/mod-lists/blob/master/modlist-descriptions.md

1. https://github.com/Ferroxius/Palette/blob/main/Alpyne.png

2. Alpyne - Ferroxius

3. https://sites.google.com/view/alpyne-skyrim/cover

4. Requires latest version of Visual C++ x64 & .Net Runtime v5 desktop x64

5. Alpyne is based in part on Althro's Tinvaak (His unreleased Tinvaak 3 which I worked on briefly shared similarities such as utilising Skyrim Redone). It is not as heavily focused however on roleplaying but does offer options to the player. It is designed with a tough but fair mindset in mind where the game still respects Skyrim's sandbox design while offering more options to the player, ensuring the game doesn't become too easy early on. It also places emphasis on reactivity within the world

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://github.com/Ferroxius/Palette/blob/main/Alpyne.webp

### When did you release the list on the Wabbajack UI?

31/05/2024 - Around four and a half months ago

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by EzioTheDeadPoet** [comment]
# Nice to have stuff

## Pre-Installation Notes

-  Documentation/Website link in `.json` links to an older markdown file that isn't for Alpyne alone (this can be set to the site submitted here on GitHub and then the website and app gallery will link to that.)
- Website even though it isn't hosted on GitHub mentions the GitHub releases section during the installation instructions, should be changed to the Gallery based instructions.
- Links on the website link to the GitHub markdown files on GitHub

## Post-Installation Notes

- Add note about NOT updating MO2.

### Gameplay Notes

- Adding an note about the choose a background chest somewhere.

### Post-Gameplay Notes

- Add Explanation about the "Warning" in MO2 with the overwrite files.

---

# Mandatory stuff

## xEdit

[CheckingErrors.log](https://github.com/user-attachments/files/17445496/CheckingErrors.log)
![image](https://github.com/user-attachments/assets/9cc7ad12-d277-458f-8843-e3c5d0abdd80)

**Comment by Ferroxius** [comment]
### Pre-Installation Notes
- Changed documentation/website link to the github readme. Better to be unified on github rather than have multiple sites

### Post-Installation Notes
- Added a section referencing MO2 updating as well as the class chest on skipping the intro

## Mandatory stuff
- Cleaned most problematic errors from tool outputs. Any remaining errors found within mod plugins have been overwritten by Conflict Resolution. Included in Alpyne v1.2.2

**Comment by EzioTheDeadPoet** [comment]
Seems good 👍 
I'll leave it to a mod or admin to apply the accepted tag. Unless someone voices some objections here.

**Comment by reyqune** [comment]
the .webp image is actually a renamed .png file and not an actual .webp file
I have included a converted version of the file that you can use:
https://cdn.discordapp.com/attachments/1200453281802104842/1297480001268092938/Alpyne.webp?ex=671613ea&is=6714c26a&hm=999518a6c8fd75aa8fa2e423936dd7dcf7b94657973676f17af41eb4090dadc9&

**Comment by Ferroxius** [comment]
Ah, I see.

I've uploaded the converted version thanks!
