### ISSUE TITLE
Featured Status Request Skyrim REMASTERED Edition

### ISSUE THREAD

**Issue by Tpiac** [wabbajack-tools/Requests-Reports#24]
### What game is your list for?

TES Skyrim Special Edition

### What is your modlist called?

Skyrim REMASTERED Edition

### Where do you offer support for your modlist?

https://discord.gg/AHW33bnUb5

### Link to readme/documentation

https://github.com/Tpiac/Skyrim-REMASTERED/blob/main/README.md

### Find A Modlist Assets and Meta Information

1 - https://github.com/Tpiac/Skyrim-REMASTERED/blob/main/Skyrim_REMASTERED_Banner.png
2 - Skyrim REMASTERED Edition / Tpiac
3 - https://github.com/Tpiac/Skyrim-REMASTERED/tree/main
4 - VC redistributable(https://aka.ms/vs/17/release/vc_redist.x64.exe)
5 - Refreshed experience with modern improvements, graphics, and gameplay features without altering the original vision and scope.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/Tpiac/Skyrim-REMASTERED/refs/heads/main/Skyrim-REMASTERED.webp

### When did you release the list on the Wabbajack UI?

Initial release at the end of 2023, it was unavailable for a time but was re-released two months ago.

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing intellectual property or brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by TDarkShadow** [comment]
On hold / rejected until #25 is fixed.
