### ISSUE TITLE
Featured Status Request Fallout 4 REMASTERED

### ISSUE THREAD

**Issue by Tpiac** [wabbajack-tools/Requests-Reports#25]
### What game is your list for?

Fallout 4

### What is your modlist called?

Fallout 4 REMASTERED

### Where do you offer support for your modlist?

https://discord.gg/AHW33bnUb5

### Link to readme/documentation

https://github.com/Tpiac/Fallout-4-REMASTERED/blob/main/README.md

### Find A Modlist Assets and Meta Information

1 - https://github.com/Tpiac/Fallout-4-REMASTERED/blob/main/Fallout4_REMASTERED.png
2 - Fallout 4 REMASTERED / Tpiac
3 - https://github.com/Tpiac/Fallout-4-REMASTERED/tree/main
4 - VC redistributable(https://aka.ms/vs/17/release/vc_redist.x64.exe)
5 - Tactical, deadly, emphasize on survival mechanics. Lore-friendly without altering original scope and vision.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/Tpiac/Fallout-4-REMASTERED/refs/heads/main/Fallout4_REMASTERED_Logo.webp

### When did you release the list on the Wabbajack UI?

Initial release at the beginning of 2024, it was unavailable for a time but was re-released a month ago.

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing intellectual property or brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by TDarkShadow** [comment]
So, I've found a couple of issues with your Readme, as of [28 Sept. 2024](https://github.com/Tpiac/Fallout-4-REMASTERED/blob/c6e6d7e7718c2ed66bd707b77aa1e7a63349b1e2/README.md).

- In the `Preparations` section, there is no mention of required English language.
- In the `Setup` section, you have a text line that's probably copy-pasted from your Skyrim REMASTERED modlist
	- As mentioned earlier, your game version on Steam should be 1.6.1170, AE Edition with downloaded CC content(launch once, download, close).
- In the `Downloading and Installing the List` section, you didn't mentioned earlier that NexusMods Premium is helpful, nor is your modlist over 1600 mods. The Wabbajack compilation downloads ~460 mods.
	- Click the start button to begin. Follow any prompts on-screen. Reiterating from earlier: if you do not have Nexus Premium, you will have to manually click through each mod. There are over 1600 mods.
- You mention the modlist uses "Stock Game", but users will not know what this means. Consider adding some explanation what it means and/or does.
	- Fallout 4 REMASTERED uses stock game in the MO2 folder.
- Might be helpful to mention whitelisting the modlist folder earlier (for modlist installation). This advice also still applies if the user doesn't use Windows Defender but another anti-virus like Sophos, Kaspersky, MalwareBytes, ...
	- If you use Windows Defender, it is advised that you set up an Exception for the entire modlist.
- The section "At the bottom, you'll find Nvidia RTX and Optional" will be unclear for users, provide some more info.
	- At the bottom of the modlist after you open Mod Organizer you will find NVIDIA RTX USERS CHECK THIS and OPTIONAL separators Switch ON & OFF Anytime
- Regarding `Widescreen And Gamepad Support`, you're not required to add it, but keep in mind that users might add an outdated mode like [Playstation 4 Buttons](https://www.nexusmods.com/fallout4/mods/395) which breaks for example FallUI mod. Consider adding some helpful mods to the modlist or in the readme, or state you don't support it at all.
- In the `Post-Installation section`, it will be unclear for first-time users how to apply MCM Settings. Add some explanation or a screenshot on how to do this.
	- In-game once you obtained control over your character apply MCM Settings in order for mods to function properly!
- All the retextures can be added to the BA2's of the Fallout 4 Stock Game folder to save space.
- All the additional LOD textures don't have to be added in MO2.
- Might be a subjective opinion, but I doubt most people have a Mouse4 and Mouse5 button.

Still play-testing the modlist so will report any feedback as soon as possible.

**Comment by Tpiac** [comment]
Thank you for your time. I have corrected the mistakes you mentioned in the readme. Your advice regarding textures will be taken into account when I update the list next time. Thanks.

**Comment by TDarkShadow** [comment]
Hey @Tpiac ,

In regards to both this Fallout 4 REMASTERED feature request and for #24 Skyrim REMASTERED, we are going to have to decline.
You have multiple piracy links in your Discord server,
you redirect users regarding Wabbajack installation errors back to the Wabbajack Discord server, without trying to troubleshoot it first,
and you still are promoting a version of the modlist with Grounded Commonwealth, which you very well know we don't allow.

Until you have solved these issues, I'll be forcing down both modlists, and both featuring requests are on hold until you comply.

With kind regards,
TDarkShadow

**Comment by Tpiac** [comment]
Thank you for your response. I don't explicitly share any piracy links on my server, although some users may do so. This issue and the second complaint can definitely be resolved. However, I'm unclear about your latest complaint regarding the GC mod. I do not affiliate with the author, nor do I include that mod in the lists hosted on Wabbajack, so I'm not sure why this is a problem. I do share a patch for GC on my Telegram, but that is unrelated to Wabbajack. Could you please clarify what steps I need to take regarding this?
