### ISSUE TITLE
Featured Status Request The Midnight Ride

### ISSUE THREAD

**Issue by Ungeziefi** [wabbajack-tools/Requests-Reports#26]
### What game is your list for?

Fallout 4

### What is your modlist called?

The Midnight Ride

### Where do you offer support for your modlist?

https://discord.gg/S99Ary5eba

### Link to readme/documentation

https://themidnightride.moddinglinked.com/wabbajack.html

### Find A Modlist Assets and Meta Information

1 - https://raw.githubusercontent.com/Ungeziefi/TMR-Wabbajack/main/Image.png
2 - The Midnight Ride, by Ungeziefi.
3 - https://themidnightride.moddinglinked.com/
4 - GOTY Edition of FO4 or the base game + all DLCs.
5 - The Midnight Ride is a modlist for Fallout 4 that will give you a perfectly stable, smooth and enjoyable experience.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/Ungeziefi/TMR-Wabbajack/main/Image.webp

### When did you release the list on the Wabbajack UI?

12/9/2024

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing intellectual property or brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by TDarkShadow** [comment]
Hey Ungeziefi, thanks for making a request.
Here is some feedback while I'm play-testing the modlist.

## Major issues
None that I have noticed.

## Minor issues
### List-related
- Users have to modify their base game installation, which will prevent them to install and play other Fallout 4 modlists.
	- This is an ongoing internal discussion wether or not this is a rejectable issue, since you did explain why The Midnight Ride doesn't use Root Builder.

## Nitpicks - personal recommendations & observations
### Documentation & Wabbajack related
- I would add a call-to-action button / link to return to the Wabbajack instructions from the Setup page, as users might continue to install The Midnight Ride manually.
- Modlist update section mentions to verify files on Steam or GOG Galaxy, while the modlist doesn't support GOG.

Will be followed up on as soon as possible regarding the downgrading post-installation step.
Looks like a great modlist, and a very intuitive website.

**Comment by Ungeziefi** [comment]
Updated the site for those 2 nitpicks, thanks.

**Comment by TDarkShadow** [comment]
Like mentioned on Discord, in the #pub channel of xNVSE, I'm going to soft-reject the request but let it open so it can be followed up on.  
We've added the requirement (https://github.com/wabbajack-tools/wiki/pull/88) that specific Bethesda games (like Fallout 4) can't have their base installation be modified due to user confusion when they try to install other modlists.  
Since yours only supports Steam anyway, you might want to use Stock Game, or use some script / MO2 plugin to symlink the necessary files.

**Comment by TDarkShadow** [comment]
I'm going to close this issue as you want to keep your own UX for your end-users.
Do reopen it (and ping me / someone in the Wabbajack Discord server) if you want to take another approach to it.
