### ISSUE TITLE
Featured Status Request Empyrean

### ISSUE THREAD

**Issue by AlabastTheSane** [wabbajack-tools/Requests-Reports#4]
### What game is your list for ?

Skyrim Special Edition

### What is your List Called ?

Empyrean

### Where do you offer support for your list ?

https://discord.gg/fgsmodlists

### Link to Readme / Documentation

https://www.fgsmodlists.com/empyrean

### Find A Modlist Assets and Meta Information

1) ![Empyrean](https://github.com/wabbajack-tools/Requests-Reports/assets/121777012/d87245fc-7fb4-4d51-ba03-37367857743f)
2) Empyrean, Alabast
3) <https://www.fgsmodlists.com/empyrean/what-is-empyrean>
4) Empyrean requires nothing more than an up to date copy of Skyrim Special Edition
For the FAL quiz and the other tools, Empyrean covers survival as a core gameplay loop, power fantasy through EnaiSiaion's mod suite, It features vanilla combat, no NSFW elements, and a focus on the player completing the main story quest, and becoming the dragonborn of legend.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://drive.google.com/file/d/1fpOjiCFFP5vBtQwcBy7TTr7tIjFaGeAb/view?usp=drive_link

### When did you release the list?

2023/06/06

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by Althro** [comment]
- Documentation is fine and it installed fine.
- Patches seem to be there and it’s load order makes sense

Will approve in 24hrs if no other comments.
