### ISSUE TITLE
Featured Status Request Heartland Redux

### ISSUE THREAD

**Issue by Drazden** [wabbajack-tools/Requests-Reports#5]
### What game is your list for ?

TES Oblivion

### What is your List Called ?

Heartland Redux

### Where do you offer support for your list ?

https://discord.gg/UCgHPE839E

### Link to Readme / Documentation

https://github.com/DrazDarkModdingHub/heartlandredux/tree/master

### Find A Modlist Assets and Meta Information

Welcome to Heartland Redux! This modlist is a fork of Heartland, originally created by Sam, which in turn was based off Bevilex's Modlist for Oblivion. Heartland has seen many changes through the years (it was one of the first Wabbajack modlists at launch!), but at its core it has remained a comprehensive graphical overhaul for The Elder Scrolls Oblivion. Redux was created by Drazden to be streamlined, sustainable, and simple.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/DrazDarkModdingHub/heartlandredux/master/imgTitle.webp

### When did you release the list?

3/26/24

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by NotTotal** [comment]
Approved in 24hrs unless anyone has something to add.

**Comment by EzioTheDeadPoet** [comment]
👍
