### ISSUE TITLE
Featured Status Request for FILFY

### ISSUE THREAD

**Issue by AllstaRawR** [wabbajack-tools/Requests-Reports#6]
### What game is your list for ?

TES Skyrim Special Edition

### What is your List Called ?

F.I.L.F.Y.

### Where do you offer support for your list ?

https://discord.gg/ag6FSESCK6

### Link to Readme / Documentation

https://github.com/AllstaRawR/FILFY/blob/main/README.md

### Find A Modlist Assets and Meta Information

1. ![FILFY_WabbajackGallery](https://github.com/wabbajack-tools/Requests-Reports/assets/164591926/9a6bf296-0fa8-4a9b-a5a5-92a1d00e3641)
2. Fantastically Integrated Load-order For You by AllstaRawR
3. [Load Order Library](https://loadorderlibrary.com/lists/filfy-fantastically-integrated-load-order-for-you)
4. Requires the full Anniversary Edition DLC.
5. The list was fully created with "The Method," via support from Elminster, Robert, etc., which means that it's completely modular. It has every mod I wanted personally and either myself or the end user can easily remove or add mods as desired. Considering the side of the list, I don't know of any other one that compares. It's not the biggest list in terms of individual mods, though it's decently close, but it's definitely the biggest one that's fully conflict resolved *individually*. Because of this I also frequently add or remove mods based off user input in the discord recommendations section.
	* There's no sex, it's intended as "Just Skyrim," it's not LoTD, it's not Requim, it is MCO, and it's unleveled. So it's not incredibly hard as a whole, but the key focus was on *a ton of added enemies and types*. So I'd say it'd go here in the chart, as "casual vanilla enemies and scaled, progressively difficult enemies in new areas". I wanted it to have a bunch of new places to explore with new enemies, of which some are hard, rather than overall difficult gameplay.
![Casual with added enemies](https://github.com/wabbajack-tools/Requests-Reports/assets/164591926/48462372-a6f5-4e65-b08f-db9e1f1b6ae7)

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/AllstaRawR/FILFY/main/images/FILFY_WabbajackGallery.webp

### When did you release the list?

3/12/2024

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by RevontuletCXVII** [comment]
Don't have any plans to use the list myself for long-term gameplay, but my testing runs have been very smooth and performed as expected with the work that was put into making it. I wholeheartedly support FILFY to be a featured list, and know that work will continue being put into fixing the very few issues it has relative to its size.

**Comment by NotTotal** [comment]
Per conversation with list author, this list is not seeking featured status until version 2.0. Will be reviewed then.
